### ISSUE TITLE
Fix README by adding assets to this repo instead of pulling them from the wiki

### ISSUE THREAD

**Issue by luzpaz** [yorikvanhavre/WebTools#17]
See https://github.com/FreeCAD/FreeCAD/issues/8361

![Screenshot_20230205_093351](https://user-images.githubusercontent.com/4140247/216825686-54ff5bcb-f771-43fb-b1b4-9799c8d6887e.png)

![Screenshot_20230205_093512](https://user-images.githubusercontent.com/4140247/216825743-d67e0f4a-dff3-4a66-9919-1cfc9b827909.png)

**Comment by yorikvanhavre** [comment]
Thanks for notifying @luzpaz !
