### ISSUE TITLE
Missing python-git

### ISSUE THREAD

**Issue by leoheck** [yorikvanhavre/WebTools#19]
Hi, I was planning to use this workbench with git to test how it works. 
However, Freecad complains about the `python-git`.
I have python3-git installed on my computer, but it looks like it is not enough.
Also, the AddonManager does not find any python package related to this workbench as you can see in the picture below.
It would be nice to add it as a dependency somehow so the AddonManager could see it and install it.

![image](https://github.com/yorikvanhavre/WebTools/assets/1277920/30235b93-9eda-4171-a720-f095f0a3c5fd)

```
[code]
OS: Ubuntu 23.04 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.33992 (Git) AppImage
Build type: Release
Branch: master
Hash: 90bafb3a069468455d8c65d030ef8750b510c39b
Python 3.10.12, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.5, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * WebTools
  * Defeaturing 1.2.0
  * Curves 0.6.13
  * fasteners 0.4.63
  * lattice2 1.0.0
  * freecad.gears 1.0.0
  * sheetmetal 0.2.63
  * Assembly4 0.50.2
  * kicadStepUpMod 10.19.4
  * Curves.backup1692246817.490895 0.6.12 (Disabled)
  * ProDarkThemePreferencePack 1.0.0
  * Help 1.0.3
[/code]

```

**Comment by leoheck** [comment]
Ah, forgot the question. How should I install python-git so the workbench find it.

**Comment by yorikvanhavre** [comment]
Indeed the addon manager was missing some info, this should be solved now.
Otherwise indeed installing python3-git should do it... In the Python console of FreeCAD, you can test by typing `import git`

**Comment by leoheck** [comment]
Isn't it possible to import git when I click on the Git button? So it will be imported when needed only but automatically.

**Comment by leoheck** [comment]
Hmm, I did not explain it right. 

The dependency you should indicate this to the Addon Manager... it will offer the installation if you do that. 
And then the process will be easier. 

I have Python git on my system but Freecad (`AppImage`) does not find anything. 

This the terminal

![image](https://github.com/yorikvanhavre/WebTools/assets/1277920/68a27c7e-57ff-41ff-b997-2a931f453e3b)

This is Freecad console

![image](https://github.com/yorikvanhavre/WebTools/assets/1277920/e76e55ad-e543-4898-bd16-eeec9b47edab)


I was talking about doing the `import git` only when you click the Git button on your toolbar. But I understood your 
message wrong, sorry. You said `import git` to test the environment not every time we wish to use the `Webttols > Git` tool.

**Comment by yorikvanhavre** [comment]
Oh right.. indeed we misunderstood each other :)
Well we could of course, but python-git is very lightweight (it's basically a small wrapper around git itself), would it be that useful to lazy-load it? Also, most python people apparently hate that :sweat_smile:
