### ISSUE TITLE
[Webtools] SVG icon for Addon Manager

### ISSUE THREAD

**Issue by luzpaz** [yorikvanhavre/WebTools#7]
https://github.com/FreeCAD/FreeCAD-addons/issues/37

**Comment by luzpaz** [comment]
@yorikvanhavre shall I post a request for a logo on the UI/UX forum ?

**Comment by yorikvanhavre** [comment]
yes good idea

**Comment by luzpaz** [comment]
https://forum.freecadweb.org/viewtopic.php?f=34&t=40130

**Comment by luzpaz** [comment]
@yorikvanhavre care to comment about the icons in the forum ?
